skills = [
    'Attack Boost',
    'Critical Eye',
    'Weakness Exploit',
    'Critical Boost',
    'Handicraft',
    'Razor Sharp',
    'Protective Polish',
    'Speed Sharpening',
    'Health Boost',
    'Recovery Up',
    'Recovery Speed',
    'Divine Blessing',
    'Evade Window',
    'Evade Extender',
    'Constitution',
    'Stamina Surge',
    'Agitator',
    'Peak Performance',
    'Resentment',
    'Heroics',
    'Fortify',
    'Free Meal',
    'Wide-Range',
    'Speed Eating',
    'Mushroomancer',
    'Item Prolonger',
    'Bombardier',
    'Artillery',
    'Special Ammo Boost',
    'Ammo Up',
    'Reload Speed',
    'Recoil Down',
    'Steadiness',
    'Rapid Fire Up',
    'Piercing Shots',
    'Spread Up',
    'Normal/Rapid Up',
    'Power Prolonger',
    'Focus',
    'Guard',
    'Guard Up',
    'Offensive Guard',
    'Counterstrike',
    'Bludgeoner',
    'Mind\'s Eye',
    'Partbreaker',
    'Slugger',
    'Stamina Thief',
    'Affinity Sliding',
    'Critical Draw',
    'Punishing Draw',
    'Quick Sheathe',
    'Marathon Runner',
    'Hunger Resistance',
    'Leap of Faith',
    'Wall Runner',
    'Master Mounter',
    'Wirebug Whisperer',
    'Geologist',
    'Botanist',
    'Master Gatherer',
    'Good Luck',
    'Carving Pro',
    'Capture Master',
    'Heat Guard',
    'Coldproof',
    'Blast Resistance',
    'Poison Resistance',
    'Paralysis Resistance',
    'Sleep Resistance',
    'Stun Resistance',
    'Muck Resistance',
    'Water Resistance',
    'Fire Resistance',
    'Ice Resistance',
    'Thunder Resistance',
    'Dragon Resistance',
    'Earplugs',
    'Windproof',
    'Tremor Resistance',
    'Bubbly Dance',
    'Resuscitate',
    'Hellfire Cloak',
    'Bloodlust',
    'Dragonheart',
    'Dereliction',
    'Mail of Hellfire',
    'Berserk',
    'Adrenaline Rush',
    'Dragon Conversion',
    'Furious',
    'Chain Crit',
    'Burst',
    'Coalescence',
    'Intrepid Heart',
    'Embolden',
    'Redirection',
    'Spiribird\'s Call',
    'Charge Master',
    'Status Trigger',
    'Foray',
    'Quick Breath',
    'Tune-Up',
    'Grinder (S)',
    'Bladescale Hone',
    'Counter Strike',
    'Razor Sharp',
    'Spare Shot',
    'Ballistics',
    'Bow Charge Plus',
    'Pierce Up',
    'Spread Up',
    'Normal Up',
    'Heavy Artillery',
    'Horn Maestro',
    'Good Luck',
    'Great Luck',
    'Carving Master',
    'Capture Master',
    'Flinch Free',
    'Jump Master',
    'Stealth',
    'Tremor Res',
    'Blight Res',
    'Blightproof',
    'Antiblast',
    'Antipara',
    'Antisleep',
    'Antistun',
    'Antipoison',
    'Antimire',
    'Aquatic Expert',
    'Cliffhanger',
    'Master Fisher',
    'Pro Transporter',
    'Honey Hunter',
    'Mycologist',
    'Lasting Power',
    'Speed Crawler',
    'Sheathing',
    'Whim',
    'Dragonvein Awakening',
    'True Dragonvein Awakening',
    'Safi\'jiiva Seal',
    'Fatalis Wings',
    'Alatreon Divinity',
    'Velkhana Divinity',
    'Teostra Blessing',
    'Kushala Blessing',
    'Chameleos Blessing',
    'Vaal Soulvein',
    'Nergigante Hunger',
    'Lunastra Favor',
    'Zorah Magdaros Essence',
    'Xeno\'jiiva Divinity',
    'Shara Ishvalda Essence',
    'Kulve Taroth Essence',
    'Behemoth Essence',
    'Leshen Essence',
    'Safi\'jiiva Essence',
    'Fatalis Essence',
    'Alatreon Essence',
    'Velkhana Essence',
    'Rajang Essence',
    'Stygian Zinogre Essence',
    'Brachydios Essence',
    'Tigrex Essence',
    'Nargacuga Essence',
    'Barioth Essence',
    'Glavenus Essence',
    'Zinogre Essence',
    'Odogaron Essence',
    'Legiana Essence',
    'Rathalos Essence',
    'Rathian Essence',
    'Diablos Essence',
    'Anjanath Essence',
    'Pukei-Pukei Essence',
    'Great Jagras Essence',
    'Kulu-Ya-Ku Essence',
    'Tzitzi-Ya-Ku Essence',
    'Paolumu Essence',
    'Radobaan Essence',
    'Uragaan Essence',
    'Lavasioth Essence',
    'Jyuratodus Essence',
    'Barroth Essence',
    'Great Girros Essence',
    'Tobi-Kadachi Essence',
    'Banbaro Essence',
    'Beotodus Essence',
    'Viper Tobi-Kadachi Essence',
    'Nightshade Paolumu Essence',
    'Coral Pukei-Pukei Essence',
    'Acidic Glavenus Essence',
    'Ebony Odogaron Essence',
    'Fulgur Anjanath Essence',
    'Shrieking Legiana Essence',
    'Seething Bazelgeuse Essence',
    'Brute Tigrex Essence',
    'Gold Rathian Essence',
    'Silver Rathalos Essence',
    'Yian Garuga Essence',
    'Scarred Yian Garuga Essence',
    'Zinogre Essence',
    'Stygian Zinogre Essence',
    'Raging Brachydios Essence',
    'Furious Rajang Essence',
    'Ruiner Nergigante Essence',
    'Blackveil Vaal Hazak Essence',
    'Namielle Essence',
    'Shara Ishvalda Essence',
    'Velkhana Essence',
    'Kushala Daora Essence',
    'Teostra Essence',
    'Lunastra Essence',
    'Chameleos Essence',
    'Alatreon Essence',
    'Fatalis Essence',
    'Safi\'jiiva Essence',
    'Kulve Taroth Essence',
    'Behemoth Essence',
    'Ancient Leshen Essence',
    'Deviljho Essence',
    'Bazelgeuse Essence',
    'Savage Deviljho Essence',
    'Seething Bazelgeuse Essence'
]